[package]
name = "print-all-items"
version = "0.1.0"
edition = "2021"

[package.metadata.rust-analyzer]
rustc_private = true

[dependencies]
rustc-plugin = { path = "../.." }
env_logger = "0.10"
clap = {version = "=3.1.18", features = ["derive"]}
serde = {version = "1", features = ["derive"]}
textwrap = "=0.15.0"
unicode-width = "=0.2.0"